README.md

Progress on https://github.com/iree-org/iree-turbine/issues/1055.

Replace root README with iree/turbine/kernel/wave/README.md.

---

iree/turbine/kernel/wave/templates/gemm.py
tests/kernel/wave/wave_gemm_test.py

This might be reused by MoE or other kernels later.

Add more datatype to GEMM kernel

---

docs/core/aot.rst
iree/turbine/kernel/wave/codegen/emitter.py
iree/turbine/kernel/wave/codegen/handlers.py
lit_tests/kernel/wave/sharktank_integration.py
wave/aot/__init__.py
wave/aot/builtins/__init__.py
wave/aot/builtins/globals.py
wave/aot/builtins/jittable.py
wave/aot/compiled_module.py
wave/aot/decompositions.py
wave/aot/exporter.py
wave/aot/fx_programs.py
wave/aot/params.py
wave/aot/passes/__init__.py
wave/aot/passes/functorch.py
wave/aot/support/ir_utils.py
wave/aot/support/procedural/__init__.py
wave/aot/support/procedural/base.py
wave/aot/support/procedural/exported_program.py
wave/aot/support/procedural/globals.py
wave/aot/support/procedural/iree_emitter.py
wave/aot/support/procedural/primitives.py
wave/aot/support/procedural/tracer.py
wave/aot/tensor_traits.py

Also run ruff on the code to make sure it
passes pre-commit.

[Wave] Migrate iree.turbine.aot -> wave.aot

---

tests/kernel/wave/attention/chained_gemm_test.py
tests/kernel/wave/reordered_gemm_test.py
tests/kernel/wave/wave_e2e_test.py
tests/kernel/wave/wave_gemm_test.py
wave_lang/kernel/wave/iree_utils.py
wave_lang/kernel/wave/profiling.py
wave_lang/kernel/wave/utils/run_utils.py

[Wave] Fix IREE benchmarking (again)

---

tests/conftest.py
wave_lang/kernel/wave/compile.py

Fix rebase error in https://github.com/iree-org/wave/pull/46 after all the renamings.

[Wave] Fix rebase error

---

lit_tests/kernel/wave/barriers.py
lit_tests/kernel/wave/gather_to_shared.py
wave_lang/kernel/wave/barriers.py
wave_lang/kernel/wave/utils/graph_utils.py

Only place barriers if shared reads/writes are to the same memory buffer.

[Wave] Improve barrier placement pass

---

lit_tests/kernel/wave/speculative_decoding.py
tests/kernel/wave/speculative_decode_test.py
wave_lang/kernel/wave/templates/speculative_decoding.py

- merged two kernels into one kernel
- updated lit test

[WAVE] Merge two kernels into one in wave speculative decode

---

tests/kernel/wave/moe_test.py
wave_lang/kernel/wave/templates/moe.py
wave_lang/kernel/wave/utils/run_utils.py

This is an implementation of MoE in wave, which matches the reference implementation in PyTorch used by SGLang.
Let's use it as a first implementation in our models and iterate from there, i.e. optimize further with quantization or kernel fusion

MoE kernel

---

docs/wave/minimize_global_loads.rst
lit_tests/kernel/wave/casting.py
tests/kernel/wave/wave_e2e_test.py

[Wave] Cleanup `elements_per_thread`

---

.github/workflows/ci-tk.yaml

To manually trigger `TK CI`, go to `Actions -> TK Ci -> Run Workflow (top right; select your branch pointing to main) -> Run Workflow `

Support for TK CI manual dispatch.

---

.github/workflows/ci.yaml
pyproject.toml
requirements.txt
setup.py
tests/conftest.py
wave_lang/kernel/wave/scheduling/aplp/pyproject.toml

This PR builds aplp in setup.py and bundles
the Rust lib as part of the wave package.

[Wave] Build aplp in setup.py

---

.github/workflows/ci-tk.yaml
tests/kernel/wave/wave_e2e_test.py
tests/kernel/wave/wave_gemm_test.py

* Remove remaining `--runperf`
* Run CI on draft PRs
* Create temp files in temp dir

[Wave] More tests cleanup

---

tests/kernel/wave/attention/prefill_attention_test.py
wave_lang/kernel/ops/wave_ops.py
wave_lang/kernel/wave/expansion/expansion.py
wave_lang/kernel/wave/generate_bounds_exprs.py
wave_lang/kernel/wave/templates/prefill_attention.py
wave_lang/kernel/wave/utils/general_utils.py

Revert "Support unaligned and unconstrained shapes in expansion"

---

lit_tests/kernel/wave/speculative_decoding.py
tests/kernel/wave/speculative_decode_test.py
wave_lang/kernel/wave/perf/benchmark_bhsd.py
wave_lang/kernel/wave/perf/benchmark_configs.json
wave_lang/kernel/wave/perf/benchmark_sdpa.py
wave_lang/kernel/wave/perf/benchmark_spda.py
wave_lang/kernel/wave/perf/benchmark_speculative_sampling.py
wave_lang/kernel/wave/perf/utils.py
wave_lang/kernel/wave/templates/speculative_decoding.py

Added speculative sampling benchmark
- renamed/refactored sdpa kernel
- removed global call in sdpa
- added spec sampling
- as per review comments, modularized the code.

[WAVE] Added speculative sampling benchmark

---

.devcontainer/Dockerfile

install rust inside the devcontainer

Install rust inside the devcontainer

---

tests/kernel/wave/dist_gemm_test.py
wave_lang/kernel/lang/global_symbols.py
wave_lang/kernel/wave/constraints.py
wave_lang/kernel/wave/templates/dist_gemm.py

This PR adds DeviceConstraint class and some boilerplate code required to further support multi-device workload.
Changes:
- New `DeviceConstraint `class - Enables tensor dimension distribution across devices with configurable tile sizes and 3D device layouts
- Updated `WorkgroupConstraint `- Added per_device_dim support to properly partition workgroups within device-local data
- Device distribution symbols - Added `DEVICE_DIM_0/1/2` global symbols for device indexing and grid computation
- Distributed GEMM template - Reference implementation demonstrating hierarchical distribution
- Updated grid computation - Modified `get_grid_shape()` to handle device constraints and added `get_device_layout()` for device grid management
Note: Changes are currently non-functional

[Dist.] DeviceConstraint infrastructure for distributed GEMM support

---

tests/kernel/wave/attention/paged_attention_test.py

Head size variables should also be updated in paged_decode_attention.py but that would be a breaking change. (Should be `head_size_qk` and `head_size_v`).

Fix reference impl in paged_attention_test.py

---

lit_tests/kernel/wave/codegen.py
wave_lang/kernel/ops/wave_ops.py
wave_lang/kernel/wave/codegen/handlers.py

add round op

---

.github/workflows/ci-gpu-rdna.yaml
requirements-iree-pinned.txt

This patch fixes RDNA CI failure after IREE bump at 09/23/2025.

Fix version mismatch after iree-bump

---

lit_tests/kernel/wave/specific_location.py
wave_lang/kernel/_support/location.py
wave_lang/kernel/ops/wave_ops.py
wave_lang/kernel/wave/analysis/index_sequence_analysis.py
wave_lang/kernel/wave/analysis/partition_strided_operators.py
wave_lang/kernel/wave/barriers.py
wave_lang/kernel/wave/debug_log_hoist.py
wave_lang/kernel/wave/decompose_dot_mma.py
wave_lang/kernel/wave/decompose_reduce_ops.py
wave_lang/kernel/wave/decompose_scan_ops.py
wave_lang/kernel/wave/decompose_vmma_ops.py
wave_lang/kernel/wave/expansion/expansion.py
wave_lang/kernel/wave/gather_to_shared.py
wave_lang/kernel/wave/global_to_shared_gathers.py
wave_lang/kernel/wave/in_thread_transpose.py
wave_lang/kernel/wave/memory_analysis/minimize_shared_allocs.py
wave_lang/kernel/wave/minimize_global_loads.py
wave_lang/kernel/wave/promotion.py
wave_lang/kernel/wave/schedule_reordering.py
wave_lang/kernel/wave/scheduling/loop_reconstruction.py
wave_lang/kernel/wave/utils/mma_utils.py

This patch fixes many places where locations were dropped during compilation. It's not necessarily exhaustive, but it gets large test cases like the codegen.py test to 100% location coverage at the end of the Wave pipeline.

[debugging] propagate locations

---

wave_lang/kernel/ops/wave_ops.py

This prevents the location loss that previously happened with this method.

[debugging] add location propagation to replace_all_uses_with
