iree-org/wave

iree/turbine/kernel/wave/cache.py, iree/turbine/kernel/wave/compile.py
This PR contains three small patches.
> [Wave] include canonicalization in the cache key
> 
> Prior to this patch, since the cache manager didn't include the
> canonicalization flag when computing the cache key, Wave occasionally
> retrieved an incorrect kernel from the cache.  Specifically, if the
> cached kernel was not run through canonicalization (since the flag is
> off by default) and if the programmer requested canonicalization, the
> programmer would still get the non-canonicalized (but cached) IR.
> 
> This patch fixes the problem by including canonicalization among the
> details that are included when computing the cache key.
and
> [Wave] support printing of cached IR
> 
> When Wave retrieves a cached kernel, we didn't check whether the
> programmer had requested that the IR be …
=> minor fixes to option handling

docs/README.md, docs/conf.py, docs/index.rst
This PR updates the titles of the docs and the links to the documentation for wave. A new read the docs site has been created that can be used to host all wave related documentation.
=> [Wave] Update documentation page

lit_tests/kernel/wave/scaled_gemm.py, lit_tests/kernel/wave/scaled_mma.py
Recent lit tests did not specify the compile_to_mlir option to be true, which meant that we were compiling the entire vmfb for the lit tests. This PR fixes that.
=> [Wave] Fix lit tests

.github/workflows/ci-tk.yaml
Timeout from config wasn't getting picked up, probably because we don't run pytest from repo root.
=> [Wave] Pass test timeout explicitly

iree/turbine/kernel/wave/utils/graph_utils.py, lit_tests/kernel/wave/dce.py
The recursion in DCE was checking only for global writes, not for other kinds of side-effects that should not be removed (such as WIP printf inside conditionals).
Signed-off-by: William G Hatch <william@hatch.uno>
=> [Wave] fix DCE

iree/turbine/kernel/wave/schedule_reordering.py, lit_tests/kernel/wave/scaled_gemm.py, tests/kernel/wave/wave_gemm_mxfp_test.py
Linear layers are typically of this format BMK,NK->BMN, previously we would have failed to determine batch dim because rhs do not have B, but with this patch, we implemented a batch filtering dimension by checking the vector_shapes from hw_constraint.
=> [Wave] Add schedule reordering support for BMK,NK->BMN

iree/turbine/kernel/wave/compile_options.py, iree/turbine/kernel/wave/utils/run_utils.py, tests/conftest.py, tests/kernel/wave/attention/alibi_attention_test.py, tests/kernel/wave/attention/chained_gemm_test.py, tests/kernel/wave/attention/decode_attention_test.py, tests/kernel/wave/attention/evoformer_test.py, tests/kernel/wave/attention/extend_attention_test.py, tests/kernel/wave/attention/gqa_vanilla_attention_test.py, tests/kernel/wave/attention/paged_attention_test.py, tests/kernel/wave/attention/prefill_attention_test.py, tests/kernel/wave/attention/quantized_attention_test.py, tests/kernel/wave/attention/t5_rpe_attention_test.py, tests/kernel/wave/attention/vanilla_attention_test.py, tests/kernel/wave/common/shapes.py, tests/kernel/wave/reordered_gemm_test.py, tests/kernel/wave/wave_e2e_test.py, tests/kernel/wave/wave_gemm_test.py
Also, `generate_iree_ref` benchmarking is currently broken due to unrelated reasons, but I will fix it later.
=> [Wave] Use pytest fixtures to get perf options instead of doing it manually each time

iree/turbine/kernel/wave/runtime/CMakeLists.txt
If users attempted to wave on OSX or Windows, the install would crash with an unsupported platform error. This PR skips the cmake build for those platforms so that the package can still be installed and lit tests can still be run.
=> [Wave] Fix builds on OSX & Windows

iree/turbine/kernel/wave/analysis/index_sequence_analysis.py, iree/turbine/kernel/wave/generate_bounds_exprs.py, iree/turbine/kernel/wave/utils/general_utils.py, lit_tests/kernel/wave/scaled_gemm.py, tests/kernel/wave/wave_gemm_mxfp_test.py
Currently scaled dimensions such as K/32 or K/2 only works on aligned shape(wrt block_k). In order to add masking/unaligned support for this we add feature to check that we have indeed scaled bound and try to scale the bound. This is most useful for handling K dims that are not power of 2 for Llama3. Main changes are:
1. Moving of `is_scaled_dim` into general_utils.py for reusability.
2. Before setting bounds, we build a map to keep all the "scaled dims", then we go through the bounds
/dim one by one, and if we find any of the dim is scaled, we apply the scaling to the bound.
=> [Wave] Teach compiler to do masking properly on scaled dims.

requirements-iree-pinned.txt, wave_lang/kernel/wave/wave.py
Contains fix for the `gather_to_lds` mismatched ranks issue (https://github.com/llvm/llvm-project/pull/149407).
=> [Wave] Update pinned iree version

docs/wave/wave.rst
In order to make docs visible, they need to be listed in the wave.rst. The trace document was not listed. This PR fixes that.
=> [Wave] Make thread trace documentation visible in docs

docs/wave/gemm_tutorial.rst
The tkl import is actually unused in this example, so an alternative is to just remove it.  However, since going from a tutorial kernel to a custom kernel is going to be a common use-case, and you are going to reach for tkl, it may be helpful to have it (especially since other tutorials that reference tkl don't specify the actual import).  But if we have it it should be correct.
=> [Wave] fix tutorial ref to tkl

lit_tests/kernel/wave/codegen.py, lit_tests/kernel/wave/scaled_gemm.py, tests/kernel/wave/wave_gemm_mxfp_test.py, wave_lang/kernel/wave/codegen/read_write.py
With the IREE bump, we can now properly use resetOffset to enable > 4GB buffer ops. It works because Wave generates:
memref.reinterpret_cast w/ workgroup offset + buffer_cast w/ resetOffset
With resetOffset, amdgpu.raw_buffer_cast will make the base pointer as the memref's base_ptr + workgroup_offset from reinterpret_cast. This makes the offsets during the read much much smaller allowing us to do > 4GB buffer loads/writes.
We also enable the tests for batched GEMM mxpf4 that has > 4GB to use bufferOps.
=> [Wave] Enable > 4GB bufferOps using resetOffset

tests/kernel/wave/wave_gemm_mxfp_test.py, tests/kernel/wave/wave_gemm_test.py, wave_lang/kernel/_support/indexing.py, wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/scheduling/graph_utils.py, wave_lang/kernel/wave/scheduling/loop_reconstruction.py, wave_lang/kernel/wave/scheduling/loop_reconstruction_utils.py, wave_lang/kernel/wave/scheduling/prefetch_scheduling.py
* For prefetch scheduling purposes, treat `GatherToLDS` as `GLOBAL_LOAD`. Add a state machine, allowing jumping `GLOBAL_LOAD` -> `LOCAL_LOAD` for `GatherToLDS` as there will no local stores. 
* Handle `GatherToLDS` in `liveness_analysis`
* Properly update `GatherToLDS`s `src_index` and `dst_index` in scheduling.
=> [Wave] Fix prefetch scheduling for `GatherToLDS`

tests/kernel/wave/wave_e2e_test.py, wave_lang/kernel/lang/wave_types.py, wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/compile.py, wave_lang/kernel/wave/debug_log_hoist.py, wave_lang/kernel/wave/utils/general_utils.py, wave_lang/kernel/wave/wave.py
This is a first step to having a convenient print op for Wave. It implicitly adds global memory kernel arguments, while also adding those memory arguments automatically in the kernel's invoke method.
=> [Wave] add debug_log_write op

tests/kernel/wave/speculative_decode_test.py, wave_lang/kernel/wave/templates/speculative_decoding.py
- updated as per the latest commits in the sglang/flashinfer speculative kernel. 
- this is without `top-p top-k`. That will be a part of the performance.
=> [WAVE] Updated wave speculativde decode as per the latest flashinfer kernel updates

wave_lang/kernel/wave/utils/run_utils.py
This error causes unit test failures on subsequent runs if cache_on is not set to 0. The issue stems from missing library context (e.g., math) when deserializing cached lambda functions.
With this workaround in place, we can proceed with submitting the PR for SGLang review.
=> Temporary fix for math library loading while using cache

wave_lang/kernel/wave/cache.py, wave_lang/kernel/wave/compile.py, wave_lang/kernel/wave/wave.py
The `anonymize_constraints()` function has a bug, in that it updates the
constraints as desired, but it doesn't return the updated constraints.
At the same time, in the caller, we use the return value of the function
to create the cache key.  Consequently, prior to this patch, we always
used `None` as the constraint portion of the cache key, so even after
updating the constraints, Wave still retrieved a stale compiled kernel
from the cache.
Additionally, prior to this change, the uncached compilation path
initialized/updated the constraints, thus causing a cache miss even
though the kernel and the programmer-specified constraints didn't
change.  Luckily, the updates to the constraints seem independent of the
trace, so this patch moves the constraint updates _before_ the cache
lookup.
=> add constraints to the cache key

lit_tests/kernel/wave/gemm.py, pytorch-cpu-requirements.txt, pytorch-rocm-requirements.txt
`torch.fx.graph.output_node` was [added in PyTorch 2.6](https://github.com/pytorch/pytorch/releases/tag/v2.6.0#:~:text=Add-,output_node,-util%20function%20to) and is used by `wave_lang.kernel.wave.schedule_reordering.insert_prefetch_loop_barriers`. That function is used by the test 
`lit_tests/kernel/wave/gemm.py:test_gemm_two_cluster_pingpong` (which also had a typo that I fixed).
And since ROCm 6.2 only supports up to PyTorch 2.5.1, the minimum ROCm version is now 6.3.
=> Bump minimum torch version to 2.6

wave_lang/kernel/wave/compile.py
Because debug_log operations require extra arguments detailed by the trace, we either need to disable the cache or save the extra debug arg info.  But since I plan to allow arbitrary closures to eventually be connected to the debug arg info (for automatic analysis, or launching of a viewer program, etc), which can not necessarily be serialized, let's just disable caching when there are debug ops.
=> disable writing to cache when there are debug_log operations

wave_lang/kernel/ops/wave_ops.py
In the original PR adding debug_log_write it originally had more arguments, and after removing them from the implementation I forgot to remove them from the type annotation.
=> fix signature of debug_log_write

.github/workflows/ci-tk.yaml, .github/workflows/ci.yaml, .github/workflows/perf.yaml
Runner capacity is shifting from MI300 to MI325 machines. These machines are compatible enough for testing, though benchmarks will need new baselines.
=> Migrate MI300 Capacity to new MI325 Capacity.

tests/kernel/wave/wave_e2e_test.py, wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/debug_log_hoist.py
In the original debug_log PR we decided to hold off on adding mappings and wait to see if they are necessary.  But practical debugging situations have now demanded that we add mappings.
=> add mappings to debug_log

wave_lang/kernel/wave/compile_options.py, wave_lang/kernel/wave/expansion/expansion.py, wave_lang/kernel/wave/expansion/expansion_utils.py, wave_lang/kernel/wave/utils/print_utils.py, wave_lang/kernel/wave/wave.py
* Add pass profiling using `cProfile`.
* Cache `get_dim_scaling` results as it's expensive.
* Reduce excessive `get_custom` in `remove_original_nodes`.
Cuts `expand_graph` time in half (3s -> 1.5s) in extend attention test.
=> [Wave] Add pass profiling and optimize `expand_graph` pass.

.github/workflows/build_and_release.yml
It would also be straightforward to add `musllinux` builds.
See https://github.com/paulzzy/wave/actions/runs/16614171122 for an example build-and-release run.
=> Re-enable `manylinux` builds with `cibuildwheel`

wave_lang/kernel/wave/compile.py, wave_lang/kernel/wave/debug_log_hoist.py
This will be helpful when there is more processing.  I originally did this in https://github.com/iree-org/wave/pull/95 but I have since decided to approach the main aspect of it in a different way, I'm pulling out this small NFC that will still be helpful for other ways to write printing / visualizingg features.
=> NFC move some reordering logic for debug logs

lit_tests/kernel/wave/casting.py, wave_lang/aot/support/ir_utils.py
When tkw.cast is used with a bool -> float the resulting cast will now be:
- true -> 1.0
- false -> 0.0
This matches the semantics for python, c++.
Previously when doing this it would have the behavior of:
- true -> -1.0
- false -> 0.0
=> [Wave] Added bool to float casting

.github/workflows/build_and_release.yml, setup.py, wave_lang/kernel/wave/runtime/CMakeLists.txt, wave_lang/kernel/wave/runtime/runtime.cpp
Enables adding the `wave-lang` package to [shark-ai](https://github.com/nod-ai/shark-ai), which uses Windows in CI.
Accomplished by supporting Windows in the Wave C++ runtime, which is the only non-portable code (everything else is Python). This also enables Windows builds.
Note that Windows testing has not been added, especially since Wave currently only supports CDNA; machines on that architecture only support Linux. In the future RDNA support will be added.
=> Support and build for Windows

lit_tests/kernel/wave/gemm.py, lit_tests/kernel/wave/multi_buffering.py, lit_tests/kernel/wave/scheduling.py, tests/kernel/wave/wave_gemm_test.py, wave_lang/kernel/wave/cache.py, wave_lang/kernel/wave/compile_options.py, wave_lang/kernel/wave/scheduling/four_stage_pipelined_scheduling.py, wave_lang/kernel/wave/scheduling/gemm_four_stage_pipelined_scheduling.py, wave_lang/kernel/wave/scheduling/loop_reconstruction.py, wave_lang/kernel/wave/scheduling/modulo_scheduling.py, wave_lang/kernel/wave/scheduling/multi_buffering.py, wave_lang/kernel/wave/scheduling/prefetch_scheduling.py, wave_lang/kernel/wave/scheduling/schedule.py, wave_lang/kernel/wave/scheduling/schedule_enums.py, wave_lang/kernel/wave/scheduling/scheduler_utils.py, wave_lang/kernel/wave/wave.py
Tested this new pipelined schedule on various tests in wave_gemm_test.py. Also modified wave_gemm_test.py correspondingly. 
Here is a representation of the type of schedule generated from a (GR, LW, LR, MMA) GEMM kernel:
```
a_0 = READ_GLOBAL 0
WRITE_SHARED a_0 SM[0]
a_1 = READ_GLOBAL 1
lds_barrier
b_0 = READ_SHARED SM[0]
WRITE_SHARED a_1 SM[1]
a_2 = READ_GLOBAL 2
lds_barrier
for i = 0 to N -3:
COMPUTE b_i
b_{i+1} = READ_SHARED SM[i+1 %2]
// Work in progress is removing the immediate subsequent lds_barrier
(lds_barrier)
WRITE_SHARED a_{i+2} SM[i%2]
a_{i+3} = READ_GLOBAL k+3
lds_barrier
COMPUTE b_{n-2}
b_{n-1} = READ_SHARED SM[n-1 %2]
WRITE_SHARED a_{n} SM[n % 2]
COMPUTE b_{n-1}
b_{n} = READ_SHARED SM[n %2]
COMPUTE b_n
```
Thank you in advance for reviewing
=> SchedulingType.FOUR_STAGE: GEMM Full Software Pipelining with Initiation Interval 1, Via Multibuffering

lit_tests/kernel/wave/gather_to_shared.py, wave_lang/kernel/wave/codegen/handlers.py
`minimize_shared_allocs` handles memref tail padding automatically, but  when it's disabled we need to handle it in lowering.
Tail-padded memrefs cannot be represented as normal allocs so allocate them as flat i8 array and take a view.
=> [Wave] Fix tail-padded memref allocs when `minimize_shared_allocs` is disabled

lit_tests/kernel/wave/gather_to_shared.py, wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/gather_to_shared.py, wave_lang/kernel/wave/wave.py
Add `GatherToLDS` swizzling. Swizzling is applied to shared memory reads index and then the inverse swizzling is applied the the `GatherToLDS` global read index (as its write index is always contiguous), "Inverse swizzling" is in fact the same formula as applying `xor` second time produces the original result.
=> [Wave] Gather to lds swizzling

docs/.readthedocs.yaml
The read the docs builds were failing ever since
we added rust to setup.py. This PR fixes that
by adding rust as a tool in the rtd yaml file.
=> Fix broken read the docs builds

lit_tests/kernel/wave/minimize_global_loads.py, tests/kernel/wave/attention/prefill_attention_test.py, wave_lang/kernel/wave/gather_to_shared.py, wave_lang/kernel/wave/global_to_shared_gathers.py, wave_lang/kernel/wave/in_thread_transpose.py, wave_lang/kernel/wave/minimize_global_loads.py
This patch fixes numerical error when the problem shape is unaligned and not constrained. During `minimize_global_loads` `materialized_shape` is used to calculate the new optimized access pattern and the issue is solved by applying padding to the unaligned dimension. We haven't encountered this issue before because the unaligned shape has always been part of the constraints.
Follow-up to https://github.com/iree-org/wave/pull/155
=> [compiler] Apply padding in `materialized_shapes`

tests/kernel/wave/wave_e2e_test.py, wave_lang/debugging/html_viewer.py, wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/compile.py, wave_lang/kernel/wave/debug_log_hoist.py, wave_lang/kernel/wave/unrolling.py, wave_lang/kernel/wave/utils/symbol_utils.py, wave_lang/kernel/wave/wave.py
This allows users to capture intermediate states during an iteration. When using extra_iteration_dimensions, output debug_log tensors have an extra dimension for each iteration axis specified.
This should allow the debug_log feature to become actually useful in many more situations.
=> [debugging] add extra_iteration_dimensions argument to debug_log

docs/wave/debugging.rst, docs/wave/wave.rst
It would be somewhat better with some screenshots of the viewer.  But since I expect the viewer to still change quickly at this point, I would rather not bloat the git repository with images that are soon going to be outdated.
This PR also documents stuff that's still pending in https://github.com/iree-org/wave/pull/180
=> [debugging][docs] add doc explaining how to use debug_log, html_viewer

lit_tests/kernel/wave/minimize_global_loads.py, lit_tests/kernel/wave/scaled_gemm.py
Two of our filecheck tests are failing when building wave with `pip install -r pytorch-cpu-requirements.txt` because they invoke IREE with `--iree-hip-target=gfx942`, which is not available in this configuration:
```
```
This PR adds enables the option `compile_to_mlir` for the respective tests which is sufficient for the filecheck tests.
=> Fix filecheck tests on non-gpu machines

lit_tests/kernel/wave/attention/pipelined_attention.py, lit_tests/kernel/wave/hoisting.py, tests/kernel/wave/attention/vanilla_attention_test.py, wave_lang/kernel/wave/hoisting.py
This PR adds support for modulo scheduling in the bshd kernels. In order to do this, it implements support for hoisting binarypyops out of iterate nodes. This was previously handled in the downstream compiler stages but we do it here to enable scheduling.
=> Add support for modulo scheduling in bshd kernels

lit_tests/kernel/wave/codegen.py, lit_tests/kernel/wave/scaled_gemm.py, wave_lang/kernel/wave/codegen/read_write.py
In this commit, we introduce memref extract strided metadata in order to get memref offset that can bring us from allocation's base address to tensor's base address.
=> [Compiler] Teach compiler to handle tensors from hal sub-allocation

wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/decompose_reduce_ops.py, wave_lang/kernel/wave/expansion/expansion.py, wave_lang/kernel/wave/utils/graph_utils.py
While reading some code to understand especially the expand_graph pass better, I decided to make some clarifications.  I've improved the docstring on the pass function to be more clear about what “expansion” means.  The code used the word “reduction” a lot for Iterate nodes, which is not wrong, but it is confusing when also I've been looking at the ReduceOp.  Renaming to relate to the Iterate op improves clarity.  Also this removes some unused code.
=> NFC improving names and docstrings for clarity

lit_tests/kernel/wave/attention/pipelined_attention.py, tests/kernel/wave/attention/vanilla_attention_test.py, wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/schedule_reordering.py, wave_lang/kernel/wave/scheduling/loop_reconstruction.py, wave_lang/kernel/wave/scheduling/prefetch_scheduling.py, wave_lang/kernel/wave/scheduling/schedule.py, wave_lang/kernel/wave/templates/vanilla_attention.py, wave_lang/kernel/wave/utils/classes.py
This PR adds the ability to add conditional barriers for attention when the PREFETCH_ATTENTION schedule is used and 8 waves are specified. Based on annotations during scheduling, operations are clustered into groups and then reordered to enable ping pong.
=> Add conditional barriers to attention schedule

wave_lang/kernel/compiler/kernel_codegen.py, wave_lang/kernel/wave/compile.py, wave_lang/kernel/wave/wave.py
- Usage of `DeviceConstraint`: Calculates device layouts, including tile sizes and device dimensions. The output is returned from the _trace_and_get_kernel_signature
- Use device_constraints when setting KernelSig, this sets the tensor dimensions for input and outputs to refer the device tile sizes that were set through DeviceConstraints instead of the problem size.
=> [Dist.] Update kernel symbols and use device layout

tests/kernel/wave/attention/paged_attention_test.py
For when CDNA 4 machines are added to CI. Tests pass on my MI355X.
=> Enable CDNA 4 in paged_attention_test.py

wave_lang/kernel/wave/utils/run_utils.py
This fixes the parsing of gpu's base name for radeon-gpu's which does not have semicolon and extra features included
the gpu-name full name that is returned by the pytorch method that wave-lang uses:
torch.cuda.get_device_properties(device).gcnArchName
Depending from the gpu-model, it may or may not include the extra properties after the gpu's base name. For example:
- "gfx90a:sramecc+:xnack", contains extra parameters after the base name "gfx90a" which tell whether or not the NACK and ecc-corrections are enabled for the gfx90a.
- "gfx1100" does not does not show the state of extra features after it's base name.
Current code parsing the gpu's base name expects that the semicolon is always included in the gpu's full name. This causes the parsing of base-name to return base-name with one …
=> hip-iree-target parsing non-colon fix

lit_tests/kernel/wave/attention/decode_attention.py, lit_tests/kernel/wave/attention/pipelined_attention.py, lit_tests/kernel/wave/codegen.py, lit_tests/kernel/wave/index_sequence_analysis.py, wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/analysis/partition_strided_operators.py, wave_lang/kernel/wave/codegen/read_write.py, wave_lang/kernel/wave/utils/general_utils.py, wave_lang/kernel/wave/utils/mapping_utils.py, wave_lang/kernel/wave/wave.py
Move gather/scatter decomposition into dedicated pass. This allows to cleanup a lot of code in read/write handlers and get rid of last traces of `vector.gather`/`scatter` there.
=> Add a dedicated pass to partition gathers/scatters

lit_tests/kernel/wave/codegen.py, wave_lang/kernel/lang/wave_types.py, wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/analysis/index_sequence_analysis.py, wave_lang/kernel/wave/codegen/handlers.py
Motivated by my topk implementation which needs broadcasted selection.
=> implement broadcasting for SelectOp

tests/kernel/wave/reordered_gemm_test.py, wave_lang/kernel/wave/templates/reordered_gemm.py
- Clamping `group_size_m` to be >= 1 to prevent empty groups, or groups of size 0.
This ensures that every division or mod has a valid, nonzero divisor and stays within bounds.
We were seeing OOB accesses otherwise for certain test cases.
- Sorted import order
- Added two additional (corner) test cases 
Resolves: [Issue 315](https://github.com/iree-org/wave/issues/315)
=> Fixes `group_size_m` in the reordered gemm.

lit_tests/kernel/wave/specific_location.py
I missed one comment on https://github.com/iree-org/wave/pull/297 about ELEMS_PER_THREAD that was unnecessary.
=> [debugging] fix minor nit in test case

lit_tests/kernel/wave/codegen.py, wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/codegen/handlers.py
- Added operator.mod to BinaryPyOp class
- Added lit_test cases for integer/float and binary lowerings
- Supports element-wise modulo on matrices/tensors
=> Added C-style modulo/remainder operator

lit_tests/kernel/wave/codegen.py, tests/kernel/wave/wave_e2e_test.py, wave_lang/kernel/ops/wave_ops.py, wave_lang/kernel/wave/codegen/handlers.py
Add dynamic indexing support for atomic operations in MoE alignment
For the MoE align block, we need support for dynamically indexed values in atomic operations. This change introduces `mapping_dynamic_vals` parameter to AtomicOp and updates the atomic operation handler to support dynamic indexing.
Key changes:
- Add `mapping_dynamic_vals` parameter to atomic operations 
- Update `handle_atomic_op` decorator to process dynamic values
- Convert dynamic registers to index-typed vectors and extract scalar indices
- Pass dynamic value dictionary to `_build_start_indices` for proper index computation
This enables atomic operations like `atomic_add` to use runtime-computed indices from input data
=> Use dynamic values for AtomicOps
